### ISSUE TITLE
codec.ContentTypeDecoder: drop hard coded default JSON

### ISSUE THREAD

**Issue by dolmen** [dolanor/rip#8]

**Comment by dolanor** [comment]
Yes. Before, everything was under a global codec registry, and json was default.
But now, we have RouteOptions, and I want it to be explicit. If you want, you could use a RouteOptionsDefault that would have JSON as the only and default codec. But otherwise, it should just fail (maybe even panic if no codec is defined).

**Comment by dolanor** [comment]
the panic has been added in bac738c
